# Generated by Django 5.0 on 2023-12-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default="Without dosaid", null=True),
        ),
    ]
