# Generated by Django 5.0 on 2023-12-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topic", "0002_alter_redactor_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(default="0", null=True),
        ),
    ]
